set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
T="$ROOT/design/targets"
A="$ROOT/art/source"
COMMON="Vertical 390x844 mobile game screenshot, portrait 9:16, rendered as a finished game screen. Art direction: real-time fracture-propagation medium drawn with procedural 2D graphics. Palette locked to sepia brown wet hardwood and pale cream fresh sawn wood, dusk woodyard sky in muted amber and slate; the ONLY green in the image is a pale sap-green used for the target band and success marks. Visible material texture: growth rings, vertical fibre lines, knot swirls, torn fuzzy fibres on split faces, flying wood dust motes. No photorealism, no painterly illustration, no 3D render, no lens flare. Flat crisp procedural shapes with fine hatched grain lines, the kind a 2D canvas renderer can actually draw. Pixel-style condensed Korean and Latin UI text, small and legible."

run () { # $1 outdir  $2 name  $3 prompt
  codex exec --sandbox workspace-write --skip-git-repo-check -C "$1" \
    "Use your image generation tool (image_gen) to create ONE image and save it as $2 in the current directory. Prompt: $3" \
    > "(log path)" 2>&1
}

run "$T" first-play.png "$COMMON A dusk woodyard. Centre of screen: one horizontal dry hardwood log resting in a low wooden cradle, seen from the side, its end grain growth rings visible at the left end and long vertical fibre lines running along its body. Painted across the log surface near its right third is a WIDE pale sap-green vertical band about 18 percent of the log length, clearly a target zone. A short iron wedge hovers above the log at the top of its bounce. Around the wedge tip a pale sap-green RING is open, thick, with a solid brighter inner arc; inside the ring the small Korean word 지금 . To the LEFT of the cradle stand THREE small iron wedges upright in the dirt, unbroken, as a physical failure budget. Behind on the left a woodpile of split billets. Bottom of the screen, in a separate dark strip clearly OUTSIDE the play area, three short guide lines of Korean text stacked: 탭 = 쐐기 박기 / 그린 링이 열릴 때 / 통나무 14개, 쐐기 3개 . Top left small counter 통나무 1/14 . Nothing is cracked yet." &

run "$T" verb-precise.png "$COMMON The instant after a PRECISE wedge strike. The iron wedge is buried deep in the top of the log, and a bright crack runs from it straight along the grain, dead straight, wide open, showing pale cream fresh wood inside the split with torn fuzzy fibres along both lips. A burst of fine wood dust sprays upward. The crack tip is still short of the pale sap-green target band painted on the log. A pale sap-green ring around the wedge with a thin tick mark on it, and beside it small Korean text 늦음 +18ms . Three upright iron wedges stand at the left of the cradle, all unbroken. Top left 통나무 6/14 . The screen reads as crisp, controlled, high impact." &

run "$T" verb-success.png "$COMMON The instant after an ORDINARY successful wedge strike. The iron wedge is set into the log but less deep, and a crack runs from it along the grain, noticeably CURVED, following the bent fibre lines, moderately open, pale cream fresh wood visible inside with ragged fibres. A light scatter of wood dust. The crack tip has advanced less far than a precise hit would, still short of the pale sap-green target band. Pale sap-green ring around the wedge with a tick mark far out on it and small Korean text 빠름 -74ms . Three upright iron wedges at the left of the cradle, one of them already snapped in half. Top left 통나무 6/14 . The screen reads as softer and messier than a clean strike." &

run "$T" verb-fail.png "$COMMON A FAILED log. The crack has run PAST the pale sap-green target band and the log has burst apart into several jagged splintered pieces flying outward, pale cream fresh wood faces exposed, long torn fibres and a heavy cloud of wood dust. The pale sap-green band is broken across the fragments. A red-brown arrow and small Korean text 12% 초과 marks the distance between the stopped crack tip and the band edge. At the left of the cradle the three iron wedges stand with TWO of them snapped and bent. The iron wedge that struck lies bounced off on the ground. Top left 통나무 6/14 . The screen reads as violent and wasteful." &

run "$T" game-over.png "$COMMON GAME OVER screen. The last log sits in the cradle with its crack FROZEN mid-run, a thin arrow drawn between the stopped crack tip and the near edge of the pale sap-green target band with the small Korean label 7% 부족 . At the top, large pixel-style Korean text 끝 · 통나무 9/14 , and under it two smaller lines 평균 정확도 0.72 and 흔들림 ±41ms . On the left of the screen a tall woodpile showing this run in one glance: neatly split billets stacked together with a few shattered ruined pieces mixed in, none removed. At the bottom a LARGE clearly drawn rectangular button with the Korean text 다시 (R) . The three iron wedges beside the cradle are all snapped. Progress is clearly stopped, this cannot be confused with a live play screen." &

run "$A" title-key.png "Square key art for a game called 결 가르기 (Grainsplit). A dusk woodyard scene: one dry hardwood log resting in a low wooden cradle, its end grain growth rings and long vertical fibre lines clearly readable, a single iron splitting wedge driven into its top with a bright crack running from the wedge along the grain, pale cream fresh wood exposed inside the split with torn fuzzy fibres and a spray of fine wood dust caught in the low amber light. A narrow pale sap-green band is painted across the log ahead of the crack tip. Three iron wedges stand upright in the dirt beside the cradle. Behind, a woodpile of split billets against a muted amber and slate sunset sky. Palette locked to sepia brown wet hardwood and pale cream sawn wood, with sap-green as the only green. Rendered as flat crisp procedural 2D graphics with fine hatched grain linework, not photorealistic, not painterly, no 3D render, no text anywhere in the image." &

wait
