set -u
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
T="$ROOT/design/targets"

SCENE="Vertical 390x844 portrait mobile game screenshot of a 2D canvas game, drawn as a finished game screen. FIXED SCENE LAYOUT, identical in every image of this set: a dusk woodyard, muted amber and slate sky with a dark treeline and stacked log piles far behind. Centre of the screen, filling most of it, ONE LARGE CIRCULAR END-GRAIN FACE of an upright hardwood log seen straight on, like a great wooden disc, resting in a low dark wooden cradle at the bottom. The disc shows concentric growth rings, radial checks, and a few dark knot swirls. An iron splitting wedge hangs point-down directly ABOVE the top edge of the disc. Palette locked to sepia brown wet hardwood and pale cream fresh sawn wood; the ONLY green anywhere is a pale sap-green horizontal band painted straight across the lower half of the disc. Style: flat crisp procedural 2D graphics with fine hatched grain linework, clean vector-like shapes, NOT photorealistic, NOT painterly, no 3D render, no lens flare. Small legible pixel-style condensed Korean and Latin UI text. Top left corner a small log counter."

run () {
  codex exec --sandbox workspace-write --skip-git-repo-check -C "$T" \
    "Use your image generation tool (image_gen) to create ONE image and save it as $1 in the current directory. Prompt: $2" \
    > "(log path)" 2>&1
}

run first-play.png "$SCENE THIS IMAGE: the very first log, nothing cracked yet, the disc is whole and unmarked. The painted sap-green band across the disc is WIDE, about 18 percent of the disc height. Around the hanging wedge a pale sap-green RING is fully open and thick, with a solid brighter inner arc, and inside the ring sits the small Korean word 지금 . To the LEFT of the cradle THREE iron wedges stand upright in the dirt, all unbroken. Top left small text 통나무 1/14 . At the very bottom of the screen, in a separate flat dark strip clearly OUTSIDE the play area, three short Korean guide lines stacked vertically: 탭 = 쐐기 박기 then 그린 링이 열릴 때 then 통나무 14개, 쐐기 3개 . Calm, waiting, nothing in motion." &

run verb-precise.png "$SCENE THIS IMAGE: the instant after a PRECISE strike. The wedge has just bitten the top edge of the disc and a crack runs from it DOWNWARD across the disc, DEAD STRAIGHT, wide open, showing pale cream fresh wood inside with torn fuzzy fibres along both lips. A bright burst of fine wood dust sprays upward from the wedge. The crack tip has travelled far but stops clearly SHORT of the sap-green band, which here is narrower, about 11 percent of the disc height. The green ring around the wedge is thinner than on an easy log, with a small tick mark on its right side and beside it small Korean text 늦음 +18ms . Three unbroken iron wedges stand left of the cradle. Top left 통나무 6/14 . Reads as crisp, controlled, high impact." &

run verb-fail.png "$SCENE THIS IMAGE: a FAILED log, shattered. The crack ran PAST the sap-green band and the disc has burst apart into several jagged wedge-shaped splinter fragments flying outward from the centre, pale cream fresh wood faces and long torn fibres exposed, a heavy cloud of wood dust and chips. The broken sap-green band is still readable across the separated fragments. A dark red-brown double-headed arrow with small Korean text 12% 초과 spans the gap between the stopped crack tip and the far edge of the band. The struck iron wedge has bounced off and lies on the ground. Left of the cradle the three iron wedges stand with TWO of them snapped in half. Top left 통나무 6/14 . Reads as violent and wasteful." &

run game-over.png "$SCENE THIS IMAGE: the GAME OVER screen, progress clearly stopped, impossible to confuse with a live play screen. The disc sits in the cradle with its crack FROZEN mid-run, and a thin arrow with the small Korean label 7% 부족 is drawn between the stopped crack tip and the near edge of the sap-green band. A dark translucent panel across the TOP of the screen carries large pixel-style Korean text 끝 · 통나무 9/14 and under it two smaller lines 평균 정확도 0.72 and 흔들림 ±41ms and a third line 결: 결 창 안에서 띠에 세운 탭 . Down the LEFT edge of the screen a tall woodpile shows the whole run at a glance: neatly split billets stacked together with several shattered ruined pieces mixed in among them, nothing removed. All three iron wedges beside the cradle are snapped. At the BOTTOM a LARGE clearly outlined rectangular button with the Korean text 다시 (R) ." &

wait
